export const ZK_MINTER_ABI = [
  {
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'verifier', type: 'address' },
    ],
    name: 'signalIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'accountIntent',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'intentId', type: 'uint256' }],
    name: 'intents',
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
      { name: 'verifier', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'paymentProof', type: 'bytes' },
      { name: 'intentId', type: 'uint256' },
    ],
    name: 'fulfillIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_intentId', type: 'uint256' }],
    name: 'cancelIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // Redeem Functions
  {
    inputs: [
      { name: '_accountNumber', type: 'string' },
      { name: '_amount', type: 'uint256' },
    ],
    name: 'signalRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_redeemId', type: 'uint256' }],
    name: 'cancelRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_redeemId', type: 'uint256' }],
    name: 'fulfillRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'redeemCount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'accountRedeemRequest',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'uint256' }],
    name: 'redeemRequests',
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'to', type: 'address' },
      { indexed: false, name: 'verifier', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'intentId', type: 'uint256' },
    ],
    name: 'IntentSignaled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'intentHash', type: 'bytes32' },
      { indexed: false, name: 'verifier', type: 'address' },
      { indexed: false, name: 'owner', type: 'address' },
      { indexed: false, name: 'to', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'IntentFulfilled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'intentId', type: 'uint256' }],
    name: 'IntentCancelled',
    type: 'event',
  },
  // Redeem Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'redeemId', type: 'uint256' },
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'accountNumber', type: 'string' },
    ],
    name: 'RedeemRequestSignaled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'redeemId', type: 'uint256' }],
    name: 'RedeemRequestFulfilled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'redeemId', type: 'uint256' }],
    name: 'RedeemRequestCancelled',
    type: 'event',
  },
  // Redeem Errors
  {
    inputs: [],
    name: 'InvalidAccountNumber',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RedeemRequestNotFound',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RedeemAlreadyExists',
    type: 'error',
  },
] as const

export const ESCROW_ABI = [
  // Core Functions
  {
    inputs: [
      { name: '_depositId', type: 'uint256' },
      { name: '_amount', type: 'uint256' },
      { name: '_to', type: 'address' },
      { name: '_verifier', type: 'address' },
      { name: '_fiatCurrency', type: 'bytes32' },
    ],
    name: 'signalIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_paymentProof', type: 'bytes' },
      { name: '_intentId', type: 'uint256' },
    ],
    name: 'fulfillIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_intentId', type: 'uint256' }],
    name: 'cancelIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_token', type: 'address' },
      { name: '_amount', type: 'uint256' },
      {
        name: '_intentAmountRange',
        type: 'tuple',
        components: [
          { name: 'min', type: 'uint256' },
          { name: 'max', type: 'uint256' },
        ],
      },
      { name: '_verifiers', type: 'address[]' },
      {
        name: '_verifierData',
        type: 'tuple[]',
        components: [
          { name: 'payeeDetails', type: 'string' },
          { name: 'data', type: 'bytes' },
        ],
      },
      {
        name: '_currencies',
        type: 'tuple[][]',
        components: [
          { name: 'code', type: 'bytes32' },
          { name: 'conversionRate', type: 'uint256' },
        ],
      },
    ],
    name: 'createDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_intentId', type: 'uint256' }],
    name: 'releaseFundsToPayer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_depositId', type: 'uint256' },
      { name: '_verifier', type: 'address' },
      { name: '_fiatCurrency', type: 'bytes32' },
      { name: '_newConversionRate', type: 'uint256' },
    ],
    name: 'updateDepositConversionRate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // View Functions
  {
    inputs: [],
    name: 'chainIdStr',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'intentCount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'depositCounter',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'intentExpirationPeriod',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'accountIntent',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '', type: 'address' },
      { name: '', type: 'uint256' },
    ],
    name: 'accountDeposits',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'uint256' }],
    name: 'intents',
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'depositId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
      { name: 'paymentVerifier', type: 'address' },
      { name: 'fiatCurrency', type: 'bytes32' },
      { name: 'conversionRate', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'uint256' }],
    name: 'deposits',
    outputs: [
      { name: 'depositor', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
      {
        name: 'intentAmountRange',
        type: 'tuple',
        components: [
          { name: 'min', type: 'uint256' },
          { name: 'max', type: 'uint256' },
        ],
      },
      { name: 'acceptingIntents', type: 'bool' },
      { name: 'remainingDeposits', type: 'uint256' },
      { name: 'outstandingIntentAmount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'uint256' },
    ],
    name: 'depositVerifiers',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'depositId', type: 'uint256' },
      { name: '', type: 'address' },
    ],
    name: 'depositVerifierData',
    outputs: [
      { name: 'payeeDetails', type: 'string' },
      { name: 'data', type: 'bytes' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'depositId', type: 'uint256' },
      { name: 'verifier', type: 'address' },
      { name: 'fiatCurrency', type: 'bytes32' },
    ],
    name: 'depositCurrencyConversionRate',
    outputs: [{ name: 'conversionRate', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'depositId', type: 'uint256' },
      { name: 'verifier', type: 'address' },
      { name: '', type: 'uint256' },
    ],
    name: 'depositCurrencies',
    outputs: [{ name: 'fiatCurrencies', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'whitelistedPaymentVerifiers',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_depositId', type: 'uint256' }],
    name: 'getDepositIntentIds',
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  // Governance Functions
  {
    inputs: [{ name: '_verifier', type: 'address' }],
    name: 'addWhitelistedPaymentVerifier',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_verifier', type: 'address' }],
    name: 'removeWhitelistedPaymentVerifier',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_intentExpirationPeriod', type: 'uint256' }],
    name: 'setIntentExpirationPeriod',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'to', type: 'address' },
      { indexed: false, name: 'verifier', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'intentId', type: 'uint256' },
    ],
    name: 'IntentSignaled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'intentHash', type: 'bytes32' },
      { indexed: false, name: 'verifier', type: 'address' },
      { indexed: false, name: 'owner', type: 'address' },
      { indexed: false, name: 'to', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'IntentFulfilled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'intentId', type: 'uint256' }],
    name: 'IntentCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'intentId', type: 'uint256' },
      { indexed: true, name: 'depositId', type: 'uint256' },
      { indexed: false, name: 'owner', type: 'address' },
      { indexed: false, name: 'to', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'IntentReleased',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'depositId', type: 'uint256' },
      { indexed: false, name: 'depositor', type: 'address' },
      { indexed: false, name: 'token', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      {
        indexed: false,
        name: 'intentAmountRange',
        type: 'tuple',
        components: [
          { name: 'min', type: 'uint256' },
          { name: 'max', type: 'uint256' },
        ],
      },
    ],
    name: 'DepositCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'depositId', type: 'uint256' },
      { indexed: true, name: 'verifier', type: 'address' },
      { indexed: false, name: 'payeeDetailsHash', type: 'bytes32' },
    ],
    name: 'DepositVerifierAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'depositId', type: 'uint256' },
      { indexed: true, name: 'verifier', type: 'address' },
      { indexed: true, name: 'currency', type: 'bytes32' },
      { indexed: false, name: 'conversionRate', type: 'uint256' },
    ],
    name: 'DepositCurrencyAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'depositId', type: 'uint256' },
      { indexed: true, name: 'verifier', type: 'address' },
      { indexed: false, name: 'fiatCurrency', type: 'bytes32' },
      { indexed: false, name: 'newConversionRate', type: 'uint256' },
    ],
    name: 'DepositConversionRateUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'verifier', type: 'address' }],
    name: 'PaymentVerifierAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'verifier', type: 'address' }],
    name: 'PaymentVerifierRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'intentExpirationPeriod', type: 'uint256' },
    ],
    name: 'IntentExpirationPeriodSet',
    type: 'event',
  },
  // Errors
  {
    inputs: [],
    name: 'InvalidAmount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidRecipient',
    type: 'error',
  },
  {
    inputs: [],
    name: 'IntentAlreadyExists',
    type: 'error',
  },
  {
    inputs: [],
    name: 'IntentNotFound',
    type: 'error',
  },
  {
    inputs: [],
    name: 'OnlyDepositor',
    type: 'error',
  },
] as const
