export const ZK_MINTER_ABI = [
  {
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'verifier', type: 'address' },
    ],
    name: 'signalIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'accountIntent',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'intentId', type: 'uint256' }],
    name: 'intents',
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
      { name: 'verifier', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'paymentProof', type: 'bytes' },
      { name: 'intentId', type: 'uint256' },
    ],
    name: 'fulfillIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_intentId', type: 'uint256' }],
    name: 'cancelIntent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // Redeem Functions
  {
    inputs: [
      { name: '_accountNumber', type: 'string' },
      { name: '_amount', type: 'uint256' },
    ],
    name: 'signalRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_redeemId', type: 'uint256' }],
    name: 'cancelRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_redeemId', type: 'uint256' }],
    name: 'fulfillRedeem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'redeemCount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'accountRedeemRequest',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'uint256' }],
    name: 'redeemRequests',
    outputs: [
      { name: 'owner', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'to', type: 'address' },
      { indexed: false, name: 'verifier', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'intentId', type: 'uint256' },
    ],
    name: 'IntentSignaled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'intentHash', type: 'bytes32' },
      { indexed: false, name: 'verifier', type: 'address' },
      { indexed: false, name: 'owner', type: 'address' },
      { indexed: false, name: 'to', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
    name: 'IntentFulfilled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'intentId', type: 'uint256' }],
    name: 'IntentCancelled',
    type: 'event',
  },
  // Redeem Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'redeemId', type: 'uint256' },
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'accountNumber', type: 'string' },
    ],
    name: 'RedeemRequestSignaled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'redeemId', type: 'uint256' }],
    name: 'RedeemRequestFulfilled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'redeemId', type: 'uint256' }],
    name: 'RedeemRequestCancelled',
    type: 'event',
  },
  // Redeem Errors
  {
    inputs: [],
    name: 'InvalidAccountNumber',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RedeemRequestNotFound',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RedeemAlreadyExists',
    type: 'error',
  },
] as const

export const ESCROW_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_owner', internalType: 'address', type: 'address' },
      {
        name: '_intentExpirationPeriod',
        internalType: 'uint256',
        type: 'uint256',
      },
      { name: '_chainName', internalType: 'string', type: 'string' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'accountDeposits',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '_account', internalType: 'address', type: 'address' }],
    name: 'accountDepositsLatest',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'accountIntent',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '_verifier', internalType: 'address', type: 'address' }],
    name: 'addWhitelistedPaymentVerifier',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_intentId', internalType: 'uint256', type: 'uint256' }],
    name: 'cancelIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'chainName',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '_token', internalType: 'contract IERC20', type: 'address' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
      {
        name: '_intentAmountRange',
        internalType: 'struct IEscrow.Range',
        type: 'tuple',
        components: [
          { name: 'min', internalType: 'uint256', type: 'uint256' },
          { name: 'max', internalType: 'uint256', type: 'uint256' },
        ],
      },
      { name: '_verifiers', internalType: 'address[]', type: 'address[]' },
      {
        name: '_verifierData',
        internalType: 'struct IEscrow.DepositVerifierData[]',
        type: 'tuple[]',
        components: [
          { name: 'payeeDetails', internalType: 'string', type: 'string' },
          { name: 'data', internalType: 'bytes', type: 'bytes' },
        ],
      },
      {
        name: '_currencies',
        internalType: 'struct IEscrow.Currency[][]',
        type: 'tuple[][]',
        components: [
          { name: 'code', internalType: 'bytes32', type: 'bytes32' },
          { name: 'conversionRate', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    name: 'createDeposit',
    outputs: [{ name: 'depositId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'depositCounter',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'depositId', internalType: 'uint256', type: 'uint256' },
      { name: 'verifier', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'depositCurrencies',
    outputs: [
      { name: 'fiatCurrencies', internalType: 'bytes32', type: 'bytes32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'depositId', internalType: 'uint256', type: 'uint256' },
      { name: 'verifier', internalType: 'address', type: 'address' },
      { name: 'fiatCurrency', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'depositCurrencyConversionRate',
    outputs: [
      { name: 'conversionRate', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'depositId', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'address', type: 'address' },
    ],
    name: 'depositVerifierData',
    outputs: [
      { name: 'payeeDetails', internalType: 'string', type: 'string' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'depositVerifiers',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'deposits',
    outputs: [
      { name: 'depositor', internalType: 'address', type: 'address' },
      { name: 'token', internalType: 'contract IERC20', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      {
        name: 'intentAmountRange',
        internalType: 'struct IEscrow.Range',
        type: 'tuple',
        components: [
          { name: 'min', internalType: 'uint256', type: 'uint256' },
          { name: 'max', internalType: 'uint256', type: 'uint256' },
        ],
      },
      { name: 'acceptingIntents', internalType: 'bool', type: 'bool' },
      { name: 'remainingDeposits', internalType: 'uint256', type: 'uint256' },
      {
        name: 'outstandingIntentAmount',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '_paymentProof', internalType: 'bytes', type: 'bytes' },
      { name: '_intentId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'fulfillIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_depositId', internalType: 'uint256', type: 'uint256' }],
    name: 'getDepositIntentIds',
    outputs: [{ name: '', internalType: 'uint256[]', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '_depositId', internalType: 'uint256', type: 'uint256' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'increaseDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'intentCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'intentExpirationPeriod',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'intents',
    outputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'depositId', internalType: 'uint256', type: 'uint256' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'timestamp', internalType: 'uint256', type: 'uint256' },
      { name: 'paymentVerifier', internalType: 'address', type: 'address' },
      { name: 'fiatCurrency', internalType: 'bytes32', type: 'bytes32' },
      { name: 'conversionRate', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'maxIntentsPerDeposit',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '_intentId', internalType: 'uint256', type: 'uint256' }],
    name: 'releaseFundsToPayer',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_verifier', internalType: 'address', type: 'address' }],
    name: 'removeWhitelistedPaymentVerifier',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: '_intentExpirationPeriod',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    name: 'setIntentExpirationPeriod',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: '_maxIntentsPerDeposit',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    name: 'setMaxIntentsPerDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: '_depositId', internalType: 'uint256', type: 'uint256' },
      { name: '_amount', internalType: 'uint256', type: 'uint256' },
      { name: '_to', internalType: 'address', type: 'address' },
      { name: '_verifier', internalType: 'address', type: 'address' },
      { name: '_fiatCurrency', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'signalIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: '_depositId', internalType: 'uint256', type: 'uint256' },
      { name: '_verifier', internalType: 'address', type: 'address' },
      { name: '_fiatCurrency', internalType: 'bytes32', type: 'bytes32' },
      { name: '_newConversionRate', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'updateDepositConversionRate',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'whitelistedPaymentVerifiers',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '_depositId', internalType: 'uint256', type: 'uint256' }],
    name: 'withdrawDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositor',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'DepositClosed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'verifier',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'fiatCurrency',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: 'newConversionRate',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'DepositConversionRateUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositor',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'token',
        internalType: 'contract IERC20',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'intentAmountRange',
        internalType: 'struct IEscrow.Range',
        type: 'tuple',
        components: [
          { name: 'min', internalType: 'uint256', type: 'uint256' },
          { name: 'max', internalType: 'uint256', type: 'uint256' },
        ],
        indexed: false,
      },
    ],
    name: 'DepositCreated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'verifier',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'currency',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'conversionRate',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'DepositCurrencyAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'depositor',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'additionalAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'newTotalAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'DepositIncreased',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'verifier',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'payeeDetailsHash',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
    ],
    name: 'DepositVerifierAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'depositor',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'DepositWithdrawn',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentCancelled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentExpirationPeriod',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentExpirationPeriodSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'verifier',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      { name: 'to', internalType: 'address', type: 'address', indexed: false },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentFulfilled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'intentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'depositId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      { name: 'to', internalType: 'address', type: 'address', indexed: false },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentReleased',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'to', internalType: 'address', type: 'address', indexed: false },
      {
        name: 'verifier',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'intentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentSignaled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'oldMax',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'newMax',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'MaxIntentsPerDepositUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'account',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'Paused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'verifier',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'PaymentVerifierAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'verifier',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'PaymentVerifierRemoved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'redeemId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'RedeemRequestCancelled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'redeemId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'RedeemRequestFulfilled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'redeemId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'accountNumber',
        internalType: 'string',
        type: 'string',
        indexed: false,
      },
    ],
    name: 'RedeemRequestSignaled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'account',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'Unpaused',
  },
  { type: 'error', inputs: [], name: 'EnforcedPause' },
  { type: 'error', inputs: [], name: 'ExpectedPause' },
  { type: 'error', inputs: [], name: 'IntentAlreadyExists' },
  { type: 'error', inputs: [], name: 'IntentNotFound' },
  { type: 'error', inputs: [], name: 'InvalidAccountNumber' },
  { type: 'error', inputs: [], name: 'InvalidAmount' },
  { type: 'error', inputs: [], name: 'InvalidRecipient' },
  { type: 'error', inputs: [], name: 'OnlyDepositor' },
  {
    type: 'error',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'OwnableInvalidOwner',
  },
  {
    type: 'error',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
  },
  { type: 'error', inputs: [], name: 'RedeemAlreadyExists' },
  { type: 'error', inputs: [], name: 'RedeemRequestNotFound' },
] as const
